name: projek_akhir_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  
  crypto: ^3.0.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2 
  intl: ^0.19.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  http: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0 
  geocoding: ^2.2.0
  sqflite: ^2.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 
  build_runner: ^2.4.8
  dart_code_metrics: ^4.19.2

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/dzaky.jpg
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Italic.ttf
          style: italic